sonar.projectKey=chrysa_guideline-checker
sonar.organization=chrysa
sonar.projectName=guideline-checker
sonar.sources=guideline_checker
sonar.tests=tests
sonar.python.version=3.14
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/.mypy_cache/**
sonar.coverage.exclusions=tests/**
