"""HTML report generator for guideline-checker results."""
from __future__ import annotations

from pathlib import Path

from guideline_checker.checker import RuleResult, Violation


_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Guideline Compliance Report</title>
<style>
  body {{ font-family: system-ui, sans-serif; margin: 0; padding: 0; background: #f8f9fa; color: #212529; }}
  header {{ background: #343a40; color: white; padding: 1.5rem 2rem; }}
  header h1 {{ margin: 0; font-size: 1.5rem; }}
  header p {{ margin: 0.25rem 0 0; opacity: 0.75; font-size: 0.9rem; }}
  .summary {{ display: flex; gap: 1rem; padding: 1.5rem 2rem; flex-wrap: wrap; }}
  .stat {{ background: white; border: 1px solid #dee2e6; border-radius: 8px; padding: 1rem 1.5rem; min-width: 120px; text-align: center; }}
  .stat .value {{ font-size: 2rem; font-weight: bold; }}
  .stat .label {{ font-size: 0.8rem; color: #6c757d; text-transform: uppercase; letter-spacing: 0.05em; }}
  .stat.error .value {{ color: #dc3545; }}
  .stat.warning .value {{ color: #fd7e14; }}
  .stat.info .value {{ color: #0d6efd; }}
  .stat.ok .value {{ color: #198754; }}
  .section {{ margin: 1rem 2rem; background: white; border: 1px solid #dee2e6; border-radius: 8px; overflow: hidden; }}
  .section-header {{ padding: 0.75rem 1.25rem; background: #e9ecef; display: flex; justify-content: space-between; align-items: center; }}
  .section-header h2 {{ margin: 0; font-size: 1rem; }}
  .section-meta {{ font-size: 0.8rem; color: #6c757d; }}
  .badge {{ display: inline-block; padding: 0.2em 0.6em; border-radius: 4px; font-size: 0.75rem; font-weight: bold; }}
  .badge-error {{ background: #f8d7da; color: #842029; }}
  .badge-warning {{ background: #fff3cd; color: #664d03; }}
  .badge-info {{ background: #cfe2ff; color: #084298; }}
  .badge-ok {{ background: #d1e7dd; color: #0a3622; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 0.875rem; }}
  th {{ background: #f8f9fa; padding: 0.5rem 1rem; text-align: left; border-bottom: 2px solid #dee2e6; }}
  td {{ padding: 0.5rem 1rem; border-bottom: 1px solid #f0f0f0; vertical-align: top; }}
  tr:hover td {{ background: #f8f9fa; }}
  .file-path {{ font-family: monospace; font-size: 0.8rem; color: #6c757d; }}
  .line-content {{ font-family: monospace; background: #f8f9fa; padding: 0.1em 0.4em; border-radius: 3px; }}
  .rule-text {{ max-width: 400px; }}
  .no-violations {{ padding: 1rem 1.25rem; color: #198754; font-size: 0.9rem; }}
  footer {{ text-align: center; color: #6c757d; font-size: 0.8rem; padding: 2rem; }}
</style>
</head>
<body>
<header>
  <h1>Guideline Compliance Report</h1>
  <p>Project: {project_root} &mdash; Generated: {generated_at}</p>
</header>
<div class="summary">
  <div class="stat ok"><div class="value">{total_files}</div><div class="label">Files checked</div></div>
  <div class="stat error"><div class="value">{total_errors}</div><div class="label">Errors</div></div>
  <div class="stat warning"><div class="value">{total_warnings}</div><div class="label">Warnings</div></div>
  <div class="stat info"><div class="value">{total_info}</div><div class="label">Info</div></div>
  <div class="stat"><div class="value">{total_rules}</div><div class="label">Rule files</div></div>
</div>
{sections}
<footer>Generated by <a href="https://github.com/chrysa/guideline-checker">guideline-checker</a></footer>
</body>
</html>
"""

_SECTION_TEMPLATE = """\
<div class="section">
  <div class="section-header">
    <div>
      <h2>{title}</h2>
      <div class="section-meta">applyTo: <code>{apply_to}</code> &mdash; {files_checked} file(s) checked</div>
    </div>
    <span class="badge {badge_class}">{badge_text}</span>
  </div>
  {body}
</div>
"""


class HtmlReporter:
    """Generate an HTML compliance report."""

    def write(self, results: list[RuleResult], output_path: Path, root: Path) -> None:
        """Write the HTML report to output_path."""
        from datetime import datetime, timezone

        generated_at = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        total_files = sum(r.files_checked for r in results)
        total_errors = sum(sum(1 for v in r.violations if v.severity == "error") for r in results)
        total_warnings = sum(sum(1 for v in r.violations if v.severity == "warning") for r in results)
        total_info = sum(sum(1 for v in r.violations if v.severity == "info") for r in results)

        sections_html = "".join(self._render_section(r, root) for r in results)

        html = _HTML_TEMPLATE.format(
            project_root=str(root),
            generated_at=generated_at,
            total_files=total_files,
            total_errors=total_errors,
            total_warnings=total_warnings,
            total_info=total_info,
            total_rules=len(results),
            sections=sections_html,
        )

        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(html, encoding="utf-8")

    def _render_section(self, result: RuleResult, root: Path) -> str:
        """Render one rule-file section."""
        title = result.instruction.description or result.instruction.path.stem
        apply_to = result.instruction.apply_to

        if not result.violations:
            badge_class = "badge-ok"
            badge_text = "PASS"
            body = '<div class="no-violations">No violations found.</div>'
        else:
            errors = sum(1 for v in result.violations if v.severity == "error")
            if errors > 0:
                badge_class = "badge-error"
                badge_text = f"{errors} error(s)"
            else:
                warnings = sum(1 for v in result.violations if v.severity == "warning")
                badge_class = "badge-warning"
                badge_text = f"{warnings} warning(s)"
            body = self._render_violations_table(result.violations, root)

        return _SECTION_TEMPLATE.format(
            title=title,
            apply_to=apply_to,
            files_checked=result.files_checked,
            badge_class=badge_class,
            badge_text=badge_text,
            body=body,
        )

    def _render_violations_table(self, violations: list[Violation], root: Path) -> str:
        """Render a table of violations."""
        rows = []
        for v in violations:
            try:
                rel_path = v.file.relative_to(root)
            except ValueError:
                rel_path = v.file
            severity_class = f"badge-{v.severity}"
            rows.append(
                f"<tr>"
                f"<td><span class='badge {severity_class}'>{v.severity.upper()}</span></td>"
                f"<td class='file-path'>{rel_path}:{v.line_number}</td>"
                f"<td class='line-content'>{_escape_html(v.line_content)}</td>"
                f"<td class='rule-text'>{_escape_html(v.rule[:150])}</td>"
                f"</tr>"
            )
        rows_html = "\n".join(rows)
        return f"""<table>
<thead><tr><th>Severity</th><th>Location</th><th>Code</th><th>Rule</th></tr></thead>
<tbody>{rows_html}</tbody>
</table>"""


def _escape_html(text: str) -> str:
    """Escape special HTML characters."""
    return (
        text
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )
