"""Markdown report generator for guideline-checker results."""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path

from guideline_checker.checker import RuleResult

_SEVERITY_EMOJI = {
    "error": "🔴",
    "warning": "🟡",
    "info": "🔵",
}


class MarkdownReporter:
    """Generate a Markdown compliance report."""

    def write(self, results: list[RuleResult], output_path: Path, root: Path) -> None:
        """Write the Markdown report to output_path."""
        generated_at = datetime.now(tz=UTC).strftime("%Y-%m-%d %H:%M UTC")
        total_files = sum(r.files_checked for r in results)
        total_errors = sum(sum(1 for v in r.violations if v.severity == "error") for r in results)
        total_warnings = sum(sum(1 for v in r.violations if v.severity == "warning") for r in results)
        total_info = sum(sum(1 for v in r.violations if v.severity == "info") for r in results)
        total_violations = total_errors + total_warnings + total_info

        lines: list[str] = [
            "# Guideline Compliance Report",
            "",
            f"**Project:** `{root}`  ",
            f"**Generated:** {generated_at}  ",
            "**Tool:** [guideline-checker](https://github.com/chrysa/guideline-checker)",
            "",
            "## Summary",
            "",
            "| Metric | Value |",
            "|--------|-------|",
            f"| Files checked | {total_files} |",
            f"| Rule files | {len(results)} |",
            f"| 🔴 Errors | {total_errors} |",
            f"| 🟡 Warnings | {total_warnings} |",
            f"| 🔵 Info | {total_info} |",
            f"| **Total violations** | **{total_violations}** |",
            "",
        ]

        if total_violations == 0:
            lines += ["## ✅ No violations found", ""]
        else:
            lines += ["## Violations by rule file", ""]
            for result in results:
                if not result.violations:
                    continue
                errors = sum(1 for v in result.violations if v.severity == "error")
                warnings = sum(1 for v in result.violations if v.severity == "warning")
                badge = f"{errors} error(s), {warnings} warning(s)"
                lines += [
                    f"### `{result.instruction.path.name}`",
                    "",
                    f"**Description:** {result.instruction.description}  ",
                    f"**Applies to:** `{result.instruction.apply_to}`  ",
                    f"**Files checked:** {result.files_checked}  ",
                    f"**Violations:** {badge}",
                    "",
                    "| Severity | File | Line | Content | Rule |",
                    "|----------|------|------|---------|------|",
                ]
                for v in result.violations:
                    rel_path = str(v.file.relative_to(root)) if v.file.is_relative_to(root) else str(v.file)
                    emoji = _SEVERITY_EMOJI.get(v.severity, "⚪")
                    content_escaped = v.line_content.replace("|", "\\|").replace("`", "'")
                    rule_escaped = v.rule.replace("|", "\\|")[:80]
                    lines.append(
                        f"| {emoji} {v.severity} | `{rel_path}` | {v.line_number} "
                        f"| `{content_escaped}` | {rule_escaped} |"
                    )
                lines.append("")

        lines += [
            "---",
            "",
            "*Generated by [guideline-checker](https://github.com/chrysa/guideline-checker)*",
        ]

        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text("\n".join(lines), encoding="utf-8")
