---
name: Dependabot Auto-merge

on:
    pull_request_target:
        types: [labeled]

concurrency:
    cancel-in-progress: false
    group: ${{ github.workflow }}-${{ github.ref }}

jobs:
    call:
        if: github.event.label.name == 'dependencies' && github.event.pull_request.user.login == 'dependabot[bot]'
        uses: chrysa/github-actions/.github/workflows/dependabot-auto-merge.yml@v1.8.0
